server:
  port: 8088
  servlet:
    context-path: /db
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/dbtest?useSSL=false
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: ooq666
    
  jpa:
    database: mysql
    hibernate:
      ddl-auto: update
    show-sql: true
  